# Generated by Django 3.1.6 on 2022-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_question_question_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
