# Generated by Django 3.1.6 on 2022-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0008_auto_20220303_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
